/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\drum-kit\models\drumset.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

useGLTF.preload('/drum-kit/models/drumset.glb')

export function Model(props) {
  const { nodes, materials } = useGLTF('/drum-kit/models/drumset.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[7.187, 35.351, 41.912]} scale={0.111}>
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0064.geometry} material={materials.phong5} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0064_1.geometry} material={materials.phongE1} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0064_2.geometry} material={materials.blinn2} />
      </group>
      <mesh geometry={nodes.chair.geometry} material={materials.lambert1} position={[9.426, 23.701, -90.043]} scale={0.111} />
      <mesh geometry={nodes.ride_tam_2.geometry} material={materials.phongE1} position={[-73.167, 107.144, 6.093]} rotation={[0, -1.402, 0]} scale={0.111}>

        {/* Ride cymbal disc is rendered by RideCymbal collider so it follows the physics body */}

        <mesh geometry={nodes.ride_tam_unit.geometry} material={materials.phongE1} position={[3.131, -18.632, -0.553]} rotation={[2.932, -1.151, 2.95]}>
          <group position={[-414.399, 96.466, 97.862]} rotation={[0.751, 0.043, -0.077]} scale={0.967}>
            <mesh geometry={nodes.polySurface1386_phongE1_01758.geometry} material={materials.phongE1} />
            <mesh geometry={nodes.polySurface1386_phongE1_01758_1.geometry} material={materials.phong5} />
            <mesh geometry={nodes.polySurface1386_phongE1_01758_2.geometry} material={materials.blinn2} />
            <mesh geometry={nodes.tam_2_rem.geometry} material={materials.phong5} position={[-35.777, 144.244, -5.781]} />
            <mesh geometry={nodes.tam_2_skind.geometry} material={materials.phong5} position={[-36.997, 138.169, -4.533]} />
          </group>
          <mesh geometry={nodes.tam_2_holder038.geometry} material={materials.phongE1} position={[-147.775, -11.073, 30.371]} rotation={[0.751, 0.043, -0.077]} scale={0.967} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.crash005.geometry} material={materials.phongE1} position={[74.038, 105.39, 3.496]} rotation={[-Math.PI, 1.451, -Math.PI]} scale={0.111}>
        <mesh geometry={nodes.crash.geometry} material={materials.phongE1} position={[0, -215.029, 0]}>

          {/* Crash cymbal disc is rendered by CrashCymbal collider so it follows the physics body */}

          <mesh geometry={nodes.tam_1_holder003.geometry} material={materials.phongE1} position={[-1.272, 239.551, 2.876]} rotation={[0, 1.167, 0]}>
            <group position={[140.556, 2.297, -80.452]} rotation={[0.778, 0.017, -0.282]} scale={0.846}>
              <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0062.geometry} material={materials.phong5} />
              <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0062_1.geometry} material={materials.phongE1} />
              <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0062_2.geometry} material={materials.blinn2} />
              <mesh geometry={nodes.tam_1_rem.geometry} material={materials.phong5} position={[303.732, 237.095, -91.866]} />
              <mesh geometry={nodes.tam_1_skind.geometry} material={materials.phong5} position={[302.124, 231.354, -91.173]} />
            </group>
          </mesh>
        </mesh>
      </mesh>
      <mesh geometry={nodes.hajhat_stativ.geometry} material={materials.phongE1} position={[81.165, 67.684, -44.457]} rotation={[0, 1.513, 0]} scale={0.111}>
        <mesh geometry={nodes.hajhat.geometry} material={materials.lambert2} position={[-8.798, 459.386, 10.005]} />
      </mesh>
      <group position={[-46.522, 50.674, -41.084]} rotation={[0, -0.861, 0]} scale={0.111}>
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0093.geometry} material={materials.phong5} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0093_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0093_2.geometry} material={materials.blinn2} />
        <mesh geometry={nodes.gulv_tam_rem.geometry} material={materials.phong5} position={[13.22, 270.858, 43.776]} />
        <mesh geometry={nodes.gulv_tam_skind.geometry} material={materials.phong5} position={[14.216, 263.413, 40.967]} />
      </group>
      <group position={[48.204, 58.796, -33.804]} rotation={[0, 0.098, 0]} scale={0.111}>
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0533.geometry} material={materials.phong5} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0533_1.geometry} material={materials.blinn2} />
        <mesh geometry={nodes.drums_lowpolySurface1269_phong5_0533_2.geometry} material={materials.phongE1} />
        <mesh geometry={nodes.lille_tromme_rem.geometry} material={materials.phong5} position={[-11.055, 242.874, 5.175]} />
        <mesh geometry={nodes.lille_tromme_skind.geometry} material={materials.phong5} position={[-8.472, 236.134, 5.228]} />
      </group>
    </group>
  )
}

useGLTF.preload('/drumset.glb')
